<?php $__env->startSection('judul','Laporan Penjualan'); ?>
<?php $__env->startSection('isi'); ?>
<div class="row">
    <div class="col-md-4"><div class="card bg-success text-white"><div class="card-body"><small>Total Penjualan Sukses</small><h3 class="font-weight-bold">Rp <?php echo e(number_format($totalPenjualan,0,',','.')); ?></h3></div></div></div>
    <div class="col-md-4"><div class="card bg-info text-white"><div class="card-body"><small>Jumlah Transaksi</small><h3 class="font-weight-bold"><?php echo e($jumlahTransaksi); ?></h3></div></div></div>
    <div class="col-md-4"><div class="card bg-danger text-white"><div class="card-body"><small>Total Retur</small><h3 class="font-weight-bold">Rp <?php echo e(number_format($totalRetur,0,',','.')); ?></h3></div></div></div>
</div>
<div class="card mb-3"><div class="card-body"><form method="GET" class="row align-items-end"><div class="col-md-4 mb-2"><label>Tanggal Awal</label><input type="date" name="tanggal_awal" value="<?php echo e($tanggalAwal); ?>" class="form-control"></div><div class="col-md-4 mb-2"><label>Tanggal Akhir</label><input type="date" name="tanggal_akhir" value="<?php echo e($tanggalAkhir); ?>" class="form-control"></div><div class="col-md-4 mb-2"><button class="btn btn-dark"><i class="fas fa-filter mr-1"></i>Tampilkan</button><button type="button" onclick="window.print()" class="btn btn-light ml-2"><i class="fas fa-print mr-1"></i>Cetak</button></div></form></div></div>
<div class="card"><div class="card-body table-responsive p-0"><table class="table table-hover mb-0"><thead><tr><th>No</th><th>Invoice</th><th>Tanggal</th><th>Kasir</th><th>Metode</th><th>Status</th><th>Total</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $penjualan; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $p): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e($loop->iteration); ?></td><td><?php echo e($p->no_invoice); ?></td><td><?php echo e($p->created_at->format('d/m/Y H:i')); ?></td><td><?php echo e($p->kasir?->name ?? '-'); ?></td><td><?php echo e(strtoupper($p->metode_pembayaran)); ?></td><td><span class="badge badge-<?php echo e($p->status_pembayaran === 'retur' ? 'danger' : 'success'); ?>"><?php echo e(strtoupper($p->status_pembayaran)); ?></span></td><td>Rp <?php echo e(number_format($p->total_harga,0,',','.')); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="text-center text-muted py-4">Tidak ada data pada periode ini.</td></tr><?php endif; ?></tbody></table></div></div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.master', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\Users\Albar\Downloads\PROJECT_KP_FUZZA_MART_FIXED\PROJECT-KP\resources\views/admin/laporan/penjualan.blade.php ENDPATH**/ ?>